module.exports = {
  rules: {
    // possible errors
    'for-direction': 1,
    'getter-return': [2, {allowImplicit: true}],
    'no-async-promise-executor': 2,
    'no-await-in-loop': 0,
    'no-compare-neg-zero': 2,
    'no-cond-assign': 2,
    'no-constant-condition': [1, {checkLoops: false}],
    'no-control-regex': 1,
    'debugger': 2,
    'no-dupe-args': 2,
    'no-dupe-else-if': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty': [1, {allowEmptyCatch: true}],
    'no-empty-character-class': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': [1, 'all', {
      conditionalAssign: false,
      returnAssign: false,
      enforeForArrowConditionals: false,
      enforceForNewInMemberExpressions: false,
      enforceForFunctionPrototypeMethods: false
    }],
    'no-extra-semi': 2,
    'no-func-assign': 2,
    'no-import-assign': 2,
    'no-inner-declarations': [2, 'both'],
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-loss-of-precision': 1,
    'no-misleading-character-class': 2,
    'no-obj-calls': 2,
    'no-promise-executor-return': 0,
    'no-prototype-builtins': 0,
    'no-regex-spaces': 1,
    'no-setter-return': 2,
    'no-sparse-arrays': 1,
    'no-template-curly-in-string': 0,
    'no-unexpected-multiline': 2,
    'no-unreachable': 1,
    'no-unreachable-loop': 2,
    'no-unsafe-finally': 2,
    'no-unsafe-negation': [2, {enforceForOrderingRelations: true}],
    'no-useless-backreference': 1,
    'require-atomic-updates': 1,
    'use-isnan': 2,
    
  }
}