module.exports = {
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint'],
  rules: {
    //--- Possible Errors
    'for-direction': 1,
    'getter-return': [2, {allowImplicit: true}],
    'no-async-promise-executor': 2,
    'no-await-in-loop': 0,
    'no-compare-neg-zero': 2,
    'no-cond-assign': 2,
    'no-constant-condition': [1, {checkLoops: false}],
    'no-control-regex': 1,
    'debugger': 2,
    'no-dupe-args': 2,
    'no-dupe-else-if': 2,
    'no-dupe-keys': 2,
    'no-duplicate-case': 2,
    'no-empty': [1, {allowEmptyCatch: true}],
    'no-empty-character-class': 2,
    'no-ex-assign': 2,
    'no-extra-boolean-cast': 2,
    'no-extra-parens': [1, 'all', {
      conditionalAssign: false,
      returnAssign: false,
      enforeForArrowConditionals: false,
      enforceForNewInMemberExpressions: false,
      enforceForFunctionPrototypeMethods: false
    }],
    'no-extra-semi': 2,
    'no-func-assign': 2,
    'no-import-assign': 2,
    'no-inner-declarations': [2, 'both'],
    'no-invalid-regexp': 2,
    'no-irregular-whitespace': 2,
    'no-loss-of-precision': 1,
    'no-misleading-character-class': 2,
    'no-obj-calls': 2,
    'no-promise-executor-return': 0,
    'no-prototype-builtins': 0,
    'no-regex-spaces': 1,
    'no-setter-return': 2,
    'no-sparse-arrays': 1,
    'no-template-curly-in-string': 0,
    'no-unexpected-multiline': 2,
    'no-unreachable': 1,
    'no-unreachable-loop': 2,
    'no-unsafe-finally': 2,
    'no-unsafe-negation': [2, {enforceForOrderingRelations: true}],
    'no-useless-backreference': 1,
    'require-atomic-updates': 1,
    'use-isnan': 2,
    'valid-typeof': 2,

    //--- best practices
    'accessor-pairs': 0,
    'array-callback-return': 2,
    'block-scoped-var': 0, // doesn't matter
    'class-methods-use-this': 2,
    'complexity': 2,
    'consistent-return': 0,
    'curly': [2, 'multi'],
    'default-case': 0,
    'default-case-last': 2,
    'default-param-last': 2,
    'dot-location': [2, 'property'],
    'dot-notation': 2,
    'eqeqeq': [2, 'smart'],
    'grouped-accessor-pairs': 2,
    'guard-for-in': 0,
    'max-classes-per-file': 0,
    'no-alert': 2,
    'no-caller': 2,
    'no-case-declarations': 2,
    'no-constructor-return': 2,
    'no-div-regex': 1,
    'no-else-return': 1,
    'no-empty-function': 1,
    'no-empty-pattern': 2,
    'no-eq-null': 0,
    'no-eval': 2,
    'no-extend-native': 2,
    'no-extra-bind': 2,
    'no-extra-label': 2,
    'no-fallthrough': 2,
    'no-floating-decimal': 0,
    'no-global-assign': 2,
    'no-implicit-coercion': 0,
    'no-implicit-globals': 0,
    'no-implied-eval': 2,
    'no-invalid-this': 2,
    'no-iterator': 2,
    'no-labels': 0,
    'no-lone-blocks': 0,
    'no-loop-func': 0,
    'no-magic-numbers': 0,
    'no-multi-spaces': 1,
    'no-multi-str': 2,
    'no-new': 0,
    'no-new-func': 2,
    'no-new-wrappers': 2,
    'no-octal': 2,
    'no-octal-escape': 2,
    'no-param-reassign': 2,
    'no-proto': 2,
    'no-redeclare': 2,
    'no-restricted-properties': 0,
    'no-return-assign': 2,
    'no-return-await': 2,
    'no-script-url': 2,
    'no-self-assign': 2,
    'no-self-compare': 2,
    'no-sequences': 2,
    'no-throw-literal': 2,
    'no-unmodified-loop-condition': 0,
    'no-unused-expressions': 1,
    'no-unused-labels': 1,
    'no-useless-call': 2,
    'no-useless-catch': 1,
    'no-useless-concat': 1,
    'no-useless-escape': 1,
    'no-useless-return': 1,
    'no-void': 1,
    'no-warning-comments': 0,
    'no-with': 2,
    'prefer-named-capture-group': 0,
    'prefer-promise-reject-errors': 0,
    'prefer-regex-literals': 1,
    'radix': 0,
    'require-await': 2,
    'require-unicode-regexp': 1,
    'vars-on-top': 0, // doesn't matter
    'wrap-iife': [2, 'inside'],
    'yoda': 2,
    'strict': 0,

  }
}